name: CI/CD Pipeline for Spring Boot

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy to AWS EC2 via SSH
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ubuntu
          sudo killall -9 java || true
          sudo docker compose down -v
          sudo docker compose up -d
          sleep 20
          nohup java -jar app.jar --spring.datasource.url=jdbc:mysql://localhost:3306/journal_db?createDatabaseIfNotExist=true --spring.datasource.username=root --spring.datasource.password=rootpassword > app.log 2>&1 &
